# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, password=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI

        :param id: The id of this InlineObject.  # noqa: E501
        :type id: str
        :param password: The password of this InlineObject.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'id': str,
            'password': str
        }

        self.attribute_map = {
            'id': 'id',
            'password': 'password'
        }

        self._id = id
        self._password = password

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object of this InlineObject.  # noqa: E501
        :rtype: InlineObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this InlineObject.

        Идентификатор пользователя  # noqa: E501

        :return: The id of this InlineObject.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineObject.

        Идентификатор пользователя  # noqa: E501

        :param id: The id of this InlineObject.
        :type id: str
        """

        self._id = id

    @property
    def password(self):
        """Gets the password of this InlineObject.


        :return: The password of this InlineObject.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this InlineObject.


        :param password: The password of this InlineObject.
        :type password: str
        """

        self._password = password
